### ISSUE TITLE
configuration.yml file should allow you do delete old queues

### ISSUE THREAD

**Issue by sax** [wanelo/lapine#4]
You should be able to deploy a change in the yaml configuration file to delete old queues. That way when you deploy changes that register new queues in place of old ones, you don't need to manually delete the old queues in the RabbitMQ admin page or on the command line.

**Comment by mattcamuto** [comment]
This would have to be an explicit delete statement block (or a cap task to delete). At my prior job we tried to do something automatic like that and deleted q's created by other apps.

**Comment by sax** [comment]
Agreed. You would need to explicitly list the queues to be deleted:

```yaml
queues:
  - q: my-app.my.queue
    ...

deleted_queues:
  - q: my-app.my.old.queue
```
